# Generated by Django 3.0.8 on 2020-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_auto_20200717_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bible',
            old_name='encode',
            new_name='enCode',
        ),
        migrations.AddField(
            model_name='bible',
            name='engName',
            field=models.CharField(default='null', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bible',
            name='book',
            field=models.CharField(max_length=300),
        ),
    ]
