# Generated by Django 3.0.8 on 2020-07-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_auto_20200717_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='bible',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='bible',
            name='text',
        ),
        migrations.RemoveField(
            model_name='bible',
            name='verse',
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.CharField(max_length=3)),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Bible')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Bible'),
        ),
    ]
