# Generated by Django 3.0.8 on 2020-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0005_auto_20200717_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='book',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='chapter',
        ),
        migrations.AddField(
            model_name='bible',
            name='chapter',
            field=models.CharField(default='null', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bible',
            name='text',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bible',
            name='verse',
            field=models.CharField(default='null', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Verse',
        ),
    ]
