# Generated by Django 3.0.8 on 2020-07-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0007_greekbible'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GreekBible',
            new_name='NA27Bible',
        ),
    ]
